### ISSUE TITLE
Write Ript Workouts

### ISSUE THREAD

**Issue by ciarawheeler** [COSC481W-2024Fall/Ript-Fitness#37]
Bodie, as a college student with little time and a user of the Ript Fitness app, wants to have the ability to choose prewritten workouts from Ript that he can access by category, length, and level.

**User:** Bodie, a college student with little time to waste and a user of the Ript Fitness app
**Feature:** A first wave of workouts that are prewritten and accessible by category and length. 
**Business Value:** Allows the user to see/try new full workouts rather than creating them on their own, or writing them in their notes app.

Task list -

- [x] Create at least 10 Ript workouts
- [x] Each workout should have a title, length, category, and level
- [x] Each workout title should be hardcoded into the frontend so we can load into the Ript workouts page when it's created

Acceptance Criteria -

1. A user can easily understand the workouts, and the UI is clean and simple.
2. Each workout is crafted and labeled correctly

**Comment by sjiang1** [comment]
Does each workout have a list of exercises?
