### ISSUE TITLE
Base Workouts class

### ISSUE THREAD

**Issue by Topher05** [COSC481W-2024Fall/Ript-Fitness#48]
# Product Backlog Item (User Story)

As a User, I want to be able to have workouts made up of exercises, so that I can remember what exercise I am doing on what day.

## Description

**Feature Name**: Base Workouts class
**Description**: This feature allows users to create and manage personalized workouts composed of various exercises. Users can add exercises to a workout, customize the number of sets and reps for each exercise, modify workout details, and delete workouts as needed for flexibility and convenience.

- User (Persona) - Macy, who wants to store workouts
- Feature (app is going to implement) - The app needs to display the data returned from the HTTP endpoint
- Business value - The user can store workouts improving the app functionality.

## Task List

1. [Task 1] Create the Workouts controller, data model, service, and repository.
2. [Task 2] Create the Add Workout feature.
3. [Task 3] Create the Update Workout feature.
4. [Task 4] Create the Delete Workout feature. (probable soft deletion)
5. [Task 5] Define database queries.
6. [Task] Test the features.

## Acceptance Criteria

- [Workouts should be able to added, updated, and deleted]
- [Workouts should be connected to accounts]
- [Workouts should have a list of exercises]

## Acceptance Tests

**Test 1**
- **Steps**: [test adding a workout]
- **Expected Outcome**: [A workout should be added to the database]

**Test 2**
- **Steps**: [test updating a workout]
- **Expected Outcome**: [A workout should be updated in the database]

**Test 2**
- **Steps**: [test deleting a workout]
- **Expected Outcome**: [A workout should be deleted in the database]

**Comment by sjiang1** [comment]
@ChrisPichlerEMU @tvanden3 
Please use this user story as an example, to list the persona, feature, and business value in your PBIs.
![Image](https://github.com/user-attachments/assets/1db7a008-ab42-4cff-8f71-7315d9641b3a)

**Comment by esnowgol** [comment]
> @ChrisPichlerEMU @tvanden3 @nhalash @esnowgol 
> Please use this user story as an example, to list the persona, feature, and business value in your PBIs.
> ![Image](https://github.com/user-attachments/assets/1db7a008-ab42-4cff-8f71-7315d9641b3a)
> 

Sorry about that! Looks like I remembered it on one pbi, and forgot it on another. I've edited my pbi to include those
